name: ✨ Feature Request
description: Suggest a feature request
title: "✨ Feat:"
labels: ["✨ Feature implementation", "👀 status: awaiting review"]
body:
  - type: textarea
    id: what-feature
    attributes:
      label: What feature?
      placeholder: Add descriptions
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      placeholder: Add screenshots
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

        - label: I want to work on this feature
